**/*

!/files/
!/.bandit.yml
!/.coveragerc
!/.github/
!/.yamllint.yml
!/README.md
!/development/default.env
!/poetry.lock
!/pyproject.toml
!/nautobot-app/
!/nautobot-app-ssot/
!/tasks.py

examples/
__pycache__/
