---
extends: "default"
rules:
  comments: "enable"
  empty-values: "disable"
  indentation:
    indent-sequences: "consistent"
  line-length: "disable"
  quoted-strings:
    quote-type: "double"
ignore: |
  .venv/
  # The following files are ignored as the {{}} causes syntax errors in yamllint
  nautobot-app/{{ cookiecutter.project_slug }}/invoke.mysql.yml
  nautobot-app/{{ cookiecutter.project_slug }}/invoke.example.yml
  nautobot-app/{{ cookiecutter.project_slug }}/mkdocs.yml
  nautobot-app-chatops/{{ cookiecutter.project_slug }}/invoke.mysql.yml
  nautobot-app-chatops/{{ cookiecutter.project_slug }}/invoke.example.yml
  nautobot-app-chatops/{{ cookiecutter.project_slug }}/invoke.mattermost.yml
  nautobot-app-chatops/{{ cookiecutter.project_slug }}/mkdocs.yml
  nautobot-app-ssot/{{ cookiecutter.project_slug }}/invoke.mysql.yml
  nautobot-app-ssot/{{ cookiecutter.project_slug }}/invoke.example.yml
  nautobot-app-ssot/{{ cookiecutter.project_slug }}/mkdocs.yml
