ARG MYSQL_VER=5.7
FROM mysql:${MYSQL_VER}

RUN yum -y update && yum install -y ca-certificates

#
# Configure SQL
#

ENV MYSQL_ROOT_PASSWORD=mostest
ENV MYSQL_USER=mmuser
ENV MYSQL_PASSWORD=mostest
ENV MYSQL_DATABASE=mattermost_test

#
# Configure Mattermost
#
WORKDIR /mm

# Copy over files
ARG MATTERMOST_VER="5.35.1"
ADD https://releases.mattermost.com/${MATTERMOST_VER}/mattermost-team-${MATTERMOST_VER}-linux-amd64.tar.gz .
RUN tar -zxvf ./mattermost-team-${MATTERMOST_VER}-linux-amd64.tar.gz
ADD mattermost_config_docker.json /mm/mattermost/config/config_docker.json
ADD mattermost-docker-entry.sh /mm/docker-entry.sh

RUN chmod +x /mm/docker-entry.sh
ENTRYPOINT /mm/docker-entry.sh

# Mattermost environment variables
ENV PATH="/mm/mattermost/bin:${PATH}"

# Create default storage directory
RUN mkdir /mm/mattermost-data
VOLUME /mm/mattermost-data

# Ports
EXPOSE 8065
