---
name: "Rebake Cookie"
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      cookie:
        description: "The cookie to rebake"
        type: "string"
        default: ""
      draft:
        description: "Whether to create the pull request as a draft"
        type: "string"
        default: ""
      pull-request:
        description: "The pull request strategy"
        type: "string"
        default: ""
      template:
        description: "The template repository URL"
        type: "string"
        default: ""
      template-dir:
        description: "The directory within the template repository to use as the template"
        type: "string"
        default: ""
      template-ref:
        description: "The branch or tag to use for the template"
        type: "string"
        default: ""
      drift-manager-tag:
        description: "The drift manager Docker image tag to use"
        type: "string"
        default: "prod"
  workflow_dispatch:
    inputs:
      cookie:
        description: "The cookie to rebake"
        type: "string"
        default: ""
      draft:
        description: "Whether to create the pull request as a draft"
        type: "string"
        default: ""
      pull-request:
        description: "The pull request strategy"
        type: "string"
        default: ""
      template:
        description: "The template repository URL"
        type: "string"
        default: ""
      template-dir:
        description: "The directory within the template repository to use as the template"
        type: "string"
        default: ""
      template-ref:
        description: "The branch or tag to use for the template"
        type: "string"
        default: ""
      drift-manager-tag:
        description: "The drift manager Docker image tag to use"
        type: "string"
        default: "prod"
jobs:
  rebake:
    runs-on: "ubuntu-22.04"
    permissions:
      actions: "write"
      contents: "write"
      packages: "read"
      pull-requests: "write"
    container: "ghcr.io/nautobot/cookiecutter-nautobot-app-drift-manager/prod:{% raw %}${{ github.event.inputs.drift-manager-tag }}{% endraw %}"
    env:
      GITHUB_TOKEN: "{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}"
    steps:
      - name: "Configure Rebake Arguments"
        id: "config"
        shell: "bash"
        run: |
          ARGS='--push'

          if [[ '{% raw %}${{ github.event.inputs.draft }}{% endraw %}' == 'true' ]]; then
            ARGS="$ARGS --draft"
          elif [[ '{% raw %}${{ github.event.inputs.draft }}{% endraw %}' == 'false' ]]; then
            ARGS="$ARGS --no-draft"
          elif [[ '{% raw %}${{ github.event.inputs.draft }}{% endraw %}' == '' ]]; then
            echo "Using repo default value for --draft"
          else
            echo "ERROR: Invalid value for draft: '{% raw %}${{ github.event.inputs.draft }}{% endraw %}'"
            exit 1
          fi

          if [[ '{% raw %}${{ github.event.inputs.pull-request }}{% endraw %}' != '' ]]; then
            ARGS="$ARGS --pull-request='{% raw %}${{ github.event.inputs.pull-request }}{% endraw %}'"
          fi

          if [[ '{% raw %}${{ github.event.inputs.template }}{% endraw %}' != '' ]]; then
            ARGS="$ARGS --template='{% raw %}${{ github.event.inputs.template }}{% endraw %}'"
          fi

          if [[ '{% raw %}${{ github.event.inputs.template-dir }}{% endraw %}' != '' ]]; then
            ARGS="$ARGS --template-dir='{% raw %}${{ github.event.inputs.template-dir }}{% endraw %}'"
          fi

          if [[ '{% raw %}${{ github.event.inputs.template-ref }}{% endraw %}' != '' ]]; then
            ARGS="$ARGS --template-ref='{% raw %}${{ github.event.inputs.template-ref }}{% endraw %}'"
          fi

          if [[ '{% raw %}${{ github.event.inputs.cookie }}{% endraw %}' == '' ]]; then
            ARGS="$ARGS '{% raw %}${{ github.repositoryUrl }}{% endraw %}'"
          else
            ARGS="$ARGS '{% raw %}${{ github.event.inputs.cookie }}{% endraw %}'"
          fi

          echo "args=$ARGS" >> $GITHUB_OUTPUT
      - name: "Rebake"
        run: |
          python -m ntc_cookie_drift_manager rebake {% raw %}${{ steps.config.outputs.args }}{% endraw %}
