---
name: "Manually initiate drift manager rebake"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      app_name:
        description: "App to rebake"
        required: true
        type: "choice"
        options:
          - "bgp-models"
          - "capacity-metrics"
          - "chatops"
          - "circuit-maintenance"
          - "data-validation-engine"
          - "design-builder"
          - "dev-example"
          - "device-lifecycle-mgmt"
          - "device-onboarding"
          - "dns-models"
          - "firewall-models"
          - "floor-plan"
          - "golden-config"
          - "netbox-importer"
          - "nornir"
          - "secrets-providers"
          - "ssot"
          - "welcome-wizard"
      tag:
        description: "Tag to rebake from. Should start with nautobot-app-v"
        required: true
        type: "string"
jobs:
  check_tag:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check that the requested tag exists"
        run: "gh release view -R nautobot/cookiecutter-nautobot-app ${{ inputs.tag }}"
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  rebake:
    needs:
      - "check_tag"
    container: "ghcr.io/nautobot/cookiecutter-nautobot-app-drift-manager/prod:latest"
    runs-on: "ubuntu-latest"
    env:
      GITHUB_TOKEN: "${{ secrets.GH_NAUTOBOT_BOT_TOKEN }}"
    steps:
      - name: "Re-bake"
        run: |
          python -m ntc_cookie_drift_manager \
            rebake \
            --push \
            --post-action=ruff \
            --post-action=poetry \
            --disable-post-actions \
            --no-draft \
            --template-ref="${{ inputs.tag }}" \
            https://github.com/nautobot/nautobot-app-${{ inputs.app_name }}.git
